# Generated by Django 3.0.7 on 2020-06-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('author_age', models.IntegerField()),
                ('author_nationality', models.CharField(max_length=20)),
                ('author_phone_number', models.IntegerField()),
            ],
        ),
    ]
