# Generated by Django 3.0.7 on 2020-06-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_user',
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
