# Generated by Django 3.0.7 on 2020-06-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200609_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.CharField(choices=[('Published', 'Published'), ('Withdrawn', 'Withdrawn'), ('Draft', 'Draft')], default='Published', max_length=20),
        ),
    ]
